#define MK_3_SPEED

#define MK_C_OFFSET_0 1
#define MK_C_INTERVAL_0 4

#define MK_C_OFFSET_1 2
#define MK_C_INTERVAL_1 2

#define MK_C_OFFSET_2 4
#define MK_C_INTERVAL_2 1

#define MK_W_OFFSET_0 1
#define MK_W_INTERVAL_0 200

#define MK_W_OFFSET_1 1
#define MK_W_INTERVAL_1 100

#define MK_W_OFFSET_2 1
#define MK_W_INTERVAL_2 16

/* #define HOLD_ON_OTHER_KEY_PRESS */
/* #define TAPPING_TERM_PER_KEY */

#define TAPPING_TERM 200
/* #define IGNORE_MOD_TAP_INTERRUPT /\* for rolling on mod-tap keys *\/ */

#define BILATERAL_COMBINATIONS
#define BILATERAL_COMBINATIONS_LIMIT_CHORD_TO_N_KEYS 4 /* GUI, Alt, Ctrl, Shift */
/* #define BILATERAL_COMBINATIONS_DELAY_MODS_THAT_MATCH MOD_MASK_GUI */
/* #define BILATERAL_COMBINATIONS_DELAY_MATCHED_MODS_BY 120  /\* ms *\/ */
#define BILATERAL_COMBINATIONS_ALLOW_CROSSOVER_AFTER 80   /* ms */
#define BILATERAL_COMBINATIONS_ALLOW_SAMESIDED_AFTER 3000 /* ms */
#define BILATERAL_COMBINATIONS_TYPING_STREAK_TIMEOUT 160  /* ms */
#define BILATERAL_COMBINATIONS_TYPING_STREAK_MODMASK (~MOD_MASK_SHIFT)
