#pragma once

#define PLOOPY_DPI_OPTIONS {300, 400, 600};
#define PLOOPY_DPI_DEFAULT 1
#define PLOOPY_DRAGSCROLL_MOMENTARY
#define PLOOPY_DRAGSCROLL_INVERT
/* #define PLOOPY_DRAGSCROLL_MULTIPLIER 0.5 */
#define PLOOPY_DRAGSCROLL_DPI 2400
#define HOLD_ON_OTHER_KEY_PRESS
#define TAPPING_TERM_PER_KEY